### ISSUE TITLE
Can't manually override get_terms orderby using "name"

### ISSUE THREAD

**Issue by solepixel** [stuttter/wp-term-order#7] opened 2016-06-17 15:45 UTC
When passing args into `get_terms()`, using `"orderby" => "name"` does not sort terms by name. If there is a specific, unconventional way to sort by name, I can't figure out what it is.

The problem appears to be due to Line 510 of wp-term-order.php:

https://github.com/stuttter/wp-term-order/blob/master/wp-term-order.php#L510

The part that is affecting overriding is:

` || in_array( $orderby, array( 'name', 't.name' ) ) `

The default of `get_terms` is "name", so trying to check for overrides using "name" won't really work, however I don't understand why "t.name" is part of this condition. Especially since Line 512 is checking for a "t.name" value

https://github.com/stuttter/wp-term-order/blob/master/wp-term-order.php#L512

Since "t.name" is part of that first condition, Line 512 will never be used because the value is being checked for in the previous condition. My suggestion would be to change the last condition from:

` || in_array( $orderby, array( 'name', 't.name' ) ) `

to

` || $orderby == 'name' `

This will at least allow you to pass "t.name" into "orderby" in `get_terms` and will sort the terms by name properly as expected. It may be a bit unconventional, but I don't know of another way to override this. Tested with latest WP version 4.5.2 and works fine.

**Comment by johnjamesjacoby** [comment] 2016-07-13 15:19
Nice catch.

This was originally a kludge because the term query could not be filtered, so ordering by a custom column was impossible without really low level request filtering that I wasn't comfortable doing.

This will need to be revisited soon, and the following changes made:
* Remove the `name` orderby override
* Default to ordering by `order` and fallback to `name` if explicitly set

**Comment by johnjamesjacoby** [comment] 2016-07-13 23:08
See also: https://core.trac.wordpress.org/ticket/35381

**Comment by johnjamesjacoby** [comment] 2016-07-13 23:13
Marking as a duplicate of #1.

**Closed by johnjamesjacoby** 2016-07-13 23:13 UTC
